CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_POINTING=y
CONFIG_PINCTRL=y
CONFIG_BT_BAS=n
CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_INTERVAL_MINUTES=30
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
