CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_POINTING=y
CONFIG_PINCTRL=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_Y=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=200
#CONFIG_PMW3610=y
#CONFIG_PMW3610_CPI=2400
#CONFIG_PMW3610_CPI_DIVIDOR=4
#CONFIG_PMW3610_ORIENTATION_180=y
#CONFIG_PMW3610_SNIPE_CPI=400
#CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4
#CONFIG_PMW3610_SCROLL_TICK=32
#CONFIG_PMW3610_INVERT_SCROLL_X=y
#CONFIG_PMW3610_INVERT_SCROLL_Y=n
#CONFIG_PMW3610_SMART_ALGORITHM=y
#CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
#CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
#CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=9600
#CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=
#CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=
#CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=
#CONFIG_PMW3610_REST3_DOWNSHIFT_TIME_MS=
#CONFIG_PMW3610_FORCE_AWAKE=n
#CONFIG_PMW3610_POLLING_RATE_125_SW=y
#CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
#CONFIG_PMW3610_MOVEMENT_THRESHOLD=0

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# display
CONFIG_ZMK_DISPLAY=y
CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_LV_Z_MEM_POOL_SIZE=8192
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n

#DYA-STUDIO
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=n

CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024



CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

CONFIG_ZMK_PMW3610_STUDIO_RPC=y
CONFIG_ZMK_PMW3610_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_STUDIO_RPC=y
CONFIG_ZMK_CUSTOM_SETTINGS_SPLIT_RPC_RELAY=y
CONFIG_ZMK_RUNTIME_MACRO=y
CONFIG_ZMK_RUNTIME_MACRO_STUDIO_RPC=y
CONFIG_ZMK_RUNTIME_COMBO=y
CONFIG_ZMK_RUNTIME_COMBO_STUDIO_RPC=y
CONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y
CONFIG_ZMK_BEHAVIOR_LOCAL_IDS_IN_BINDINGS=y
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=4096
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=256
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256
CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=256
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6000
CONFIG_ZMK_CUSTOM_SETTINGS_LARGE_VALUE_MAX_SIZE=256
